### PR TITLE
MAINT-52285: Add html id for different stats in profiel-stats-portlet for auto tests in ci/cd

### PR DESCRIPTION
**Pull request by eromdhaneexo**
Add html id for different stats in profile-stats-portlet for auto tests in ci/cd

### CODE REVIEW

**Review by rdenarie — CHANGES_REQUESTED** [review]
The commit message is KO.

**Comment by rdenarie** [comment]
@hakermi Can you take in charge this backport in order to have a correct commit message, which respect the guidelines (correct title, answer WHY ? and HOW ? questions)
Thanks

**Comment by hakermi** [comment]
> @hakermi Can you take in charge this backport in order to have a correct commit message, which respect the guidelines (correct title, answer WHY ? and HOW ? questions) Thanks

@rdenarie Could you check?

**Comment by rdenarie** [comment]
@hakermi it is still ko.
Please follow the guidelines : https://developer.exoplatform.org/#id-contributions

Your commit message should answer WHY and HOW questions

**Comment by hakermi** [comment]
> 

It looks responding on **how=> add html ids** and **why=> for ci/cd auto tests**
if you want more details, so could you add it in the task as you are the creator ?

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
