### PR TITLE
fix: Migration from 6.3 to 6.4,user does not have permission to announce a challenge - EXO-62903 - Meeds-io/meeds#846

### PR DESCRIPTION
**Pull request by IlhemEssaadi**
Prior to this change, when the user announced a challenge with version 6.3.5 and then migrated to version 6.4, he was not allowed to announce the same challenge because in version 6.3 it is the challenge that has an audience and not the program.After this change, the announcement was successfully published.

### CODE REVIEW

**Comment by boubaker** [comment]
AFAIK, this is expected to not being able to announce a challenge not being part of a program with an audience anymore. @srenault-meeds correct me please if I'm wrong.

**Comment by srenault-meeds** [comment]
Yes indeed @IlhemEssaadi 
This has to be done by interface by functional consultant or by reward admin.
cc @margondicco please can you make sure exo team doesn't change business rules regarding gamification without telling us so we coordinate ourselves the solution?

**Comment by Jihed525** [comment]
@srenault-meeds this PR was treated as reported in your exo-feedback https://community.exoplatform.com/portal/dw/tasks/taskDetail/62740 for migration cases and it was considered as High Priority, it is no longer needed ?
I might have missed a detail @margondicco @boubaker ?

**Comment by rdenarie** [comment]
Hello
@Jihed525 In fact, there is a real problem after 6.4.0 migration
But, the provided fix does not follow the correct way because it seems that it revert a wanted feature.

I start a deeper analysis on customer environment which where migrated to try to find the exact problem.

**Pull request closed without merging**
