### PR TITLE
Tasks to develop

### PR DESCRIPTION
**Pull request by GouadriaHanen**

### CODE REVIEW

**Review by azayati — DISMISSED** [review]
Don't forget to modify the PR title to be used later as commit message when merging cc @GouadriaHanen @ahamdi

**Comment by ahamdi** [comment]
> Don't forget to modify the PR title to be used later as commit message when merging cc @GouadriaHanen @ahamdi

@azayati Thanks for the review, Those commits will be merged without squash, thus this commit won't be stored in Git hitory

**Review by ahamdi — DISMISSED** [review]

**Review by ahamdi — APPROVED** [review]
LGTM

**Comment by hbenali** [comment]
@GouadriaHanen Please proceed with direct push 

```bash
git fetch 
git push origin origin/TasksTOdevelop:develop
```
Thanks

**Pull request merged**
