### PR TITLE
Some labels are missing in dw homepage on the gamification gadget

### PR DESCRIPTION
**Pull request by rdenarie**
To address this issue, we remove the gamification properties without suffixe, because the default file is Gamification_en.properties.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
Shouldn't you also add back the strings removed in https://github.com/Meeds-io/gamification/commit/dd1936b307360d94c77748e52fe8b00c9205f9ba#diff-1b1cb9ad0f221960ddcb71ff9cfcb638L300-L306 ?

**Comment by rdenarie** [comment]
This label is present in Gamification_en.properties : 
https://github.com/Meeds-io/gamification/blob/develop/services/src/main/resources/locale/addon/Gamification_en.properties#L20

**Comment by thomasdelhomenie** [comment]
I don't see "homepage.profileStatus.header" and the following ones, is it expected ?

**Comment by rdenarie** [comment]
Good catch. I removed the file but did not readd the missing labels.

**Review by thomasdelhomenie — APPROVED** [review]

**Pull request merged**
